runtime: nodejs16
service: default

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /(.*)
  secure: always
  redirect_http_response_code: 301
  script: auto